# Generated by Django 5.1.4 on 2025-07-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_builder', '0002_alter_project_options_alter_projectfile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_generation_status',
            field=models.CharField(choices=[('ready', 'Ready'), ('generating', 'Generating'), ('completed', 'Completed'), ('error', 'Error')], default='ready', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='django_project_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='last_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='main_app_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='ai_merge_status',
            field=models.CharField(choices=[('none', 'No AI Content'), ('new', 'New AI Generated'), ('merged', 'Merged with Existing'), ('conflict', 'Merge Conflict')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='original_content',
            field=models.TextField(blank=True),
        ),
    ]
