# Generated by Django 5.1.4 on 2025-07-16 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_builder', '0003_project_ai_generation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 16, 16, 33, 46, 316054, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
