# Generated by Django 5.1.4 on 2025-07-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_builder', '0004_chatmessage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='complexity_level',
            field=models.CharField(choices=[('simple', 'Simple (1-3 models)'), ('medium', 'Medium (4-8 models)'), ('complex', 'Complex (9+ models)'), ('enterprise', 'Enterprise (Advanced features)')], default='simple', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='generated_features',
            field=models.JSONField(blank=True, default=list, help_text='Features that have been implemented'),
        ),
        migrations.AddField(
            model_name='project',
            name='key_features',
            field=models.JSONField(blank=True, default=list, help_text='List of main features requested'),
        ),
        migrations.AddField(
            model_name='project',
            name='original_prompt',
            field=models.TextField(blank=True, help_text='The initial user request'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('web_app', 'Web Application'), ('api', 'API Service'), ('blog', 'Blog/CMS'), ('ecommerce', 'E-commerce'), ('dashboard', 'Dashboard/Analytics'), ('social', 'Social Platform'), ('portfolio', 'Portfolio Site'), ('business', 'Business Management'), ('education', 'Educational Platform'), ('entertainment', 'Entertainment/Media'), ('custom', 'Custom Application')], default='custom', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='prompt_history',
            field=models.JSONField(blank=True, default=list, help_text='History of all user prompts'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_audience',
            field=models.CharField(blank=True, help_text='Who will use this application?', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='technical_requirements',
            field=models.JSONField(blank=True, default=dict, help_text='Special technical needs'),
        ),
    ]
