# Generated by Django 5.1.4 on 2025-07-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_builder', '0002_chatthread_update_chatmessage'),
        ('ai_builder', '0005_project_complexity_level_project_generated_features_and_more'),
    ]

    operations = [
    ]
