# Generated by Django 5.2.4 on 2025-07-18 20:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_builder', '0006_merge_20250717_1621'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_builder.chatthread'),
        ),
        migrations.CreateModel(
            name='ProjectSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('files_modified', models.IntegerField(default=0)),
                ('commands_executed', models.IntegerField(default=0)),
                ('errors_encountered', models.IntegerField(default=0)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='ai_builder.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('syntax', 'Syntax Error'), ('import', 'Import Error'), ('runtime', 'Runtime Error'), ('database', 'Database Error'), ('network', 'Network Error'), ('permission', 'Permission Error'), ('container', 'Container Error'), ('other', 'Other Error')], max_length=20)),
                ('error_message', models.TextField()),
                ('error_traceback', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('command_executed', models.CharField(blank=True, max_length=500)),
                ('user_action', models.CharField(blank=True, max_length=200)),
                ('is_resolved', models.BooleanField(default=False)),
                ('auto_fix_attempted', models.BooleanField(default=False)),
                ('auto_fix_successful', models.BooleanField(default=False)),
                ('fix_description', models.TextField(blank=True)),
                ('fix_applied_at', models.DateTimeField(blank=True, null=True)),
                ('claude_thread_used', models.UUIDField(blank=True, null=True)),
                ('tokens_used_for_fix', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='ai_builder.project')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_builder.projectsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project_type', models.CharField(max_length=20)),
                ('complexity_level', models.CharField(max_length=20)),
                ('template_data', models.JSONField(default=dict)),
                ('times_used', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('is_public', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('source_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_builder.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='dark', max_length=20)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German')], default='en', max_length=10)),
                ('total_projects_created', models.IntegerField(default=0)),
                ('total_ai_requests', models.IntegerField(default=0)),
                ('total_tokens_used', models.BigIntegerField(default=0)),
                ('default_project_type', models.CharField(blank=True, max_length=20)),
                ('default_complexity', models.CharField(default='simple', max_length=20)),
                ('auto_fix_errors', models.BooleanField(default=True)),
                ('enable_analytics', models.BooleanField(default=True)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('monthly_token_limit', models.BigIntegerField(default=100000)),
                ('monthly_tokens_used', models.BigIntegerField(default=0)),
                ('billing_cycle_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsageAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('project_create', 'Project Created'), ('ai_generation', 'AI Generation'), ('file_edit', 'File Edited'), ('command_run', 'Command Executed'), ('container_start', 'Container Started'), ('error_occurred', 'Error Occurred'), ('error_fixed', 'Error Fixed'), ('session_start', 'Session Started'), ('session_end', 'Session Ended')], max_length=20)),
                ('action_data', models.JSONField(default=dict)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('user_agent', models.TextField(blank=True)),
                ('page_url', models.URLField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_builder.project')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_builder.projectsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='ai_builder__user_id_603a99_idx'), models.Index(fields=['action_type', '-timestamp'], name='ai_builder__action__c3e8d8_idx'), models.Index(fields=['project', '-timestamp'], name='ai_builder__project_7712ac_idx')],
            },
        ),
    ]
