# Generated by Django 5.2.4 on 2025-07-21 20:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_builder', '0008_userprofile_avatar_userprofile_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('enterprise', 'Enterprise')], max_length=20)),
                ('token_limit', models.BigIntegerField(help_text='Token limit per billing cycle (0 = unlimited)')),
                ('bonus_tokens', models.BigIntegerField(default=0, help_text='Additional tokens given on signup')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one_time', 'One Time')], default='monthly', max_length=20)),
                ('max_projects', models.IntegerField(default=10, help_text='Maximum number of projects (0 = unlimited)')),
                ('max_concurrent_containers', models.IntegerField(default=1)),
                ('advanced_features', models.JSONField(default=dict, help_text='Advanced features enabled')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default_free', models.BooleanField(default=False, help_text='Default plan for new users')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField()),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('auto_renew', models.BooleanField(default=True)),
                ('tokens_used_this_period', models.BigIntegerField(default=0)),
                ('bonus_tokens_remaining', models.BigIntegerField(default=0)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=200)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('next_payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai_builder.billingplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('subscription_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('token_overage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tokens_included', models.BigIntegerField()),
                ('tokens_used', models.BigIntegerField()),
                ('tokens_overage', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('canceled', 'Canceled')], default='draft', max_length=20)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=200)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai_builder.usersubscription')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('ai_generation', 'AI Code Generation'), ('chat_message', 'Chat Message'), ('error_fix', 'Auto Error Fix'), ('file_analysis', 'File Analysis'), ('project_planning', 'Project Planning'), ('code_review', 'Code Review'), ('other', 'Other')], max_length=20)),
                ('tokens_used', models.IntegerField()),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('operation_description', models.CharField(blank=True, max_length=200)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('cost_cents', models.IntegerField(default=0, help_text='Cost in cents')),
                ('billing_period', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_builder.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_builder.usersubscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_builder__user_id_725223_idx'), models.Index(fields=['subscription', '-created_at'], name='ai_builder__subscri_27df0e_idx'), models.Index(fields=['billing_period', 'user'], name='ai_builder__billing_1bf442_idx'), models.Index(fields=['usage_type', '-created_at'], name='ai_builder__usage_t_d0e842_idx')],
            },
        ),
    ]
