# Generated by Django 5.2.4 on 2025-07-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_builder', '0009_billingplan_usersubscription_billinginvoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingplan',
            name='advanced_features',
        ),
        migrations.AddField(
            model_name='billingplan',
            name='enable_advanced_templates',
            field=models.BooleanField(default=False, help_text='Access to advanced project templates'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='enable_ai_chat',
            field=models.BooleanField(default=True, help_text='Enable AI chat functionality'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='enable_analytics',
            field=models.BooleanField(default=False, help_text='Advanced usage analytics'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='enable_api_access',
            field=models.BooleanField(default=False, help_text='API access for external integrations'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='enable_auto_error_fix',
            field=models.BooleanField(default=False, help_text='Enable automatic error fixing'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='enable_code_export',
            field=models.BooleanField(default=True, help_text='Export generated code'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='enable_collaboration',
            field=models.BooleanField(default=False, help_text='Team collaboration features'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='enable_custom_containers',
            field=models.BooleanField(default=False, help_text='Use custom Docker configurations'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='enable_custom_models',
            field=models.BooleanField(default=False, help_text='Access to different AI models'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='enable_priority_support',
            field=models.BooleanField(default=False, help_text='Priority customer support'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='enable_version_control',
            field=models.BooleanField(default=False, help_text='Git integration and version control'),
        ),
        migrations.AddField(
            model_name='billingplan',
            name='enable_white_labeling',
            field=models.BooleanField(default=False, help_text='White-label customization'),
        ),
    ]
