# Generated by Django 5.2.4 on 2025-07-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_builder', '0011_add_payment_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='ai_builder__user_id_4b4e26_idx',
            old_name='ai_builder_payment_user_id_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='ai_builder__status_e443e4_idx',
            old_name='ai_builder_payment_status_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='ai_builder__payment_2e9411_idx',
            old_name='ai_builder_payment_payment_method_id_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='ai_builder__referen_c37284_idx',
            old_name='ai_builder_payment_reference_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='ai_builder__transac_0bc3eb_idx',
            old_name='ai_builder_payment_transaction_hash_idx',
        ),
    ]
