# Generated by Django 5.2.4 on 2025-07-24 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='Upload a profile picture', upload_to='avatars/', verbose_name='Profile Picture')),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself', max_length=500, verbose_name='Biography')),
                ('location', models.CharField(blank=True, help_text='Where are you located?', max_length=100, verbose_name='Location')),
                ('website', models.URLField(blank=True, help_text='Your personal website or blog', verbose_name='Website')),
                ('following', models.ManyToManyField(blank=True, help_text='Users that this profile is following', related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Following')),
                ('user', models.OneToOneField(help_text='User associated with this profile', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-user__date_joined'],
            },
        ),
    ]
