import docker
import os
import shutil
from pathlib import Path
from django.conf import settings
import subprocess
import time
import logging
import platform
import json
import uuid
import socket
logger = logging.getLogger(__name__)


class ContainerService:
    def __init__(self):
        try:
            # For Windows, try different Docker connection methods
            logger.info(platform.system())
            if platform.system() == "Windows":
                try:
                    # Try named pipe first (Docker Desktop default)
                    self.client = docker.from_env()
                except:
                    # Try TCP connection as fallback
                    self.client = docker.DockerClient(base_url='tcp://localhost:2375')
            else:
                self.client = docker.from_env()
                
            # Test connection
            self.client.ping()
            logger.info("Docker client initialized successfully")
            
        except Exception as e:
            logger.error(f"Failed to initialize Docker client: {e}")
            self.client = None
        
        self.projects_dir = Path(settings.USER_PROJECTS_DIR)
        self.projects_dir.mkdir(exist_ok=True)
        
    def create_django_project(self, project_name: str, project_id: str, app_name: str = None) -> dict:
        """Create a new Django project directory with startproject and startapp"""
        project_path = self.projects_dir / project_id
        
        try:
            # Create project directory
            project_path.mkdir(parents=True, exist_ok=True)
            
            # Save current directory
            original_dir = os.getcwd()
            
            # Change to project directory
            os.chdir(project_path)
            
            # Create the Django project with proper naming
            clean_project_name = project_name.replace(' ', '_').lower()
            
            # Ensure we use a consistent project name that won't conflict with app names
            django_project_name = f"{clean_project_name}_project"
            
            cmd = ['django-admin', 'startproject', django_project_name, '.']
            result = subprocess.run(cmd, check=True, capture_output=True, text=True)
            logger.info(f"Created Django project '{django_project_name}': {result.stdout}")
            
            # Create main app if app_name provided
            if app_name:
                clean_app_name = app_name.replace(' ', '_').lower()
                # Ensure app name doesn't conflict with project name
                if clean_app_name == django_project_name:
                    clean_app_name = f"{clean_app_name}_app"
                
                app_cmd = ['python', 'manage.py', 'startapp', clean_app_name]
                app_result = subprocess.run(app_cmd, check=True, capture_output=True, text=True)
                logger.info(f"Created Django app '{clean_app_name}': {app_result.stdout}")
            else:
                clean_app_name = 'main'
                app_cmd = ['python', 'manage.py', 'startapp', clean_app_name]
                app_result = subprocess.run(app_cmd, check=True, capture_output=True, text=True)
                logger.info(f"Created default Django app '{clean_app_name}': {app_result.stdout}")
            
            # Requirements.txt should be generated by SmartProjectGenerator
            # If it doesn't exist, create minimal fallback
            requirements_file = project_path / 'requirements.txt'
            if not requirements_file.exists():
                logger.warning("No requirements.txt found, creating minimal fallback")
                requirements_content = """Django==5.0.7
python-dotenv==1.0.1
"""
                with open(requirements_file, 'w') as f:
                    f.write(requirements_content)
            
            # Create .env file
            env_content = f"""DEBUG=True
SECRET_KEY=django-insecure-{project_id}
ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
"""
            with open(project_path / '.env', 'w') as f:
                f.write(env_content)
            
            # Restore original directory
            os.chdir(original_dir)
            
            return {
                'success': True,
                'project_path': str(project_path),
                'project_name': clean_project_name,
                'django_project_name': django_project_name,
                'app_name': clean_app_name,
                'files_created': self._scan_created_files(project_path)
            }
            
        except subprocess.CalledProcessError as e:
            logger.error(f"Failed to create Django project: {e}")
            return {
                'success': False,
                'error': f"Failed to create Django project: {e}",
                'stderr': e.stderr if hasattr(e, 'stderr') else str(e)
            }
        except Exception as e:
            logger.error(f"Error creating project: {e}")
            return {
                'success': False,
                'error': str(e)
            }
        finally:
            # Ensure we restore the original directory
            try:
                os.chdir(original_dir)
            except:
                pass
    
    def _scan_created_files(self, project_path: Path) -> list:
        """Scan and return list of files created in the project"""
        files = []
        if not project_path.exists():
            return files
        
        try:
            for file_path in project_path.rglob('*'):
                if file_path.is_file() and not self._should_ignore_file(file_path):
                    relative_path = file_path.relative_to(project_path)
                    files.append({
                        'path': str(relative_path),
                        'size': file_path.stat().st_size,
                        'type': file_path.suffix.lstrip('.') if file_path.suffix else 'txt'
                    })
        except Exception as e:
            logger.error(f"Error scanning files: {e}")
        
        return files
    
    def start_container(self, project_id: str, port: int = None, stream_callback=None) -> dict:
        """Start a Django development container"""
        if not self.client:
            return {'error': 'Docker client not available. Please start Docker Desktop.'}

        project_path = self.projects_dir / project_id

        if not project_path.exists():
            return {'error': 'Project directory not found'}

        try:
            # Stop any existing container
            self.stop_container(project_id)
            
            # Find available port
            if port is None:
                port = self._find_available_port()

            # Sanitize and define image tag
            image_tag = f"django-project-{project_id}".lower().replace(" ", "-")

            # Get the correct settings module name first
            settings_module = self._get_settings_module(project_path)
            logger.info(f"Detected settings module: {settings_module}")

            # Create Dockerfile
            dockerfile_content = f"""FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \\
    build-essential \\
    libpq-dev \\
    gcc \\
    python3-dev \\
    curl \\
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

COPY requirements.txt ./
RUN echo "Installing Python packages from requirements.txt..." && \
    cat requirements.txt && \
    pip install --no-cache-dir --verbose -r requirements.txt && \
    echo "Python packages installed successfully" && \
    pip list
COPY . .

EXPOSE 8000

ENV DJANGO_SETTINGS_MODULE={settings_module}

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

"""
            dockerfile_path = project_path / 'Dockerfile'
            dockerfile_path.write_text(dockerfile_content)
            requirements_file = project_path / 'requirements.txt'
            if not requirements_file.exists():
                raise FileNotFoundError(f"Missing requirements.txt at {requirements_file}")
            # Build Docker image
            logger.info(f"Building Docker image for project {project_id}...")
            if stream_callback:
                stream_callback(f"Building Docker image for project {project_id}...\n")
            
            logs = self.client.api.build(
                path=str(project_path),
                tag=image_tag,
                rm=True,
                forcerm=True,
                # buildargs={"CACHE_BUST": str(uuid.uuid4())},
                decode=True
            )

            # Check build output for errors and stream to frontend
            for chunk in logs:
                if 'stream' in chunk:
                    log_text = chunk['stream']
                    print(log_text, end='')
                    if stream_callback:
                        stream_callback(log_text)
                elif 'error' in chunk:
                    error_text = f"Build error: {chunk['error']}\n"
                    logger.error(error_text)
                    if stream_callback:
                        stream_callback(error_text)
                    return {'error': chunk['error'], 'status': 'failed'}

            # Verify the image was created
            images = self.client.images.list(name=image_tag)
            if not any(image_tag in tag for image in images for tag in image.tags):
                return {'error': f"Docker image '{image_tag}' not found after build.", 'status': 'failed'}

            # Run the container
            logger.info(f"Starting container for project {project_id}")
            if stream_callback:
                stream_callback(f"Starting container for project {project_id}...\n")
            
            container = self.client.containers.run(
                image=image_tag,
                ports={'8000/tcp': port},
                volumes={str(project_path): {'bind': '/app', 'mode': 'rw'}},
                name=f"django-container-{project_id}",
                detach=True,
                # remove=True,
                environment={
                    'PYTHONUNBUFFERED': '1'
                }
            )

            # Allow time for container to boot and Django server to start
            time.sleep(8)

            # Get container info for debugging
            container.reload()
            port_info = container.attrs['NetworkSettings']['Ports']
            logger.info(f"Container port mapping: {port_info}")
            if stream_callback:
                stream_callback(f"Container port mapping: {port_info}\n")

            # Get initial logs without complex streaming
            if stream_callback:
                try:
                    # Get initial logs
                    initial_logs = container.logs(stream=False, tail=50).decode('utf-8')
                    stream_callback(initial_logs)
                    stream_callback("Container started successfully. Logs will be available in the terminal.\n")
                except Exception as e:
                    logger.error(f"Error getting initial logs: {e}")
                    stream_callback(f"Container started but log streaming failed: {e}\n")
            
            # Get logs to check for errors
            logs = container.logs(stream=False, tail=50).decode('utf-8')
            logger.info(f"Container logs: {logs}")
            
            # Check if there are any startup errors
            error_indicators = [
                'ModuleNotFoundError', 'ImportError', 'Error:', 'Exception:', 
                'Traceback', 'CommandError', 'SystemExit',
                "Couldn't import Django", 'No module named'
            ]
            
            has_errors = any(error in logs for error in error_indicators)
            
            if has_errors:
                logger.error(f"Container startup error: {logs}")
                if stream_callback:
                    stream_callback(f"❌ Container startup failed with errors:\n{logs}\n")
                return {
                    'error': f"Container startup failed: {logs}",
                    'status': 'failed'
                }
            
            # Check if Django server started successfully - look for multiple possible startup indicators
            server_started = (
                'Starting development server' in logs or 
                'Django version' in logs or
                'Watching for file changes' in logs or
                'System check' in logs or
                'http://0.0.0.0:8000/' in logs
            )
            
            if server_started:
                logger.info(f"Django server started successfully on port {port}")
                if stream_callback:
                    stream_callback(f"✅ Django server started successfully on port {port}\n")
            else:
                logger.warning(f"Django server startup not detected in logs")
                if stream_callback:
                    stream_callback(f"⚠️ Django server startup not detected in logs\n")
                    stream_callback(f"📋 Container logs for debugging:\n{logs[:500]}...\n")

            return {
                'container_id': container.id,
                'port': port,
                'status': 'running'
            }

        except Exception as e:
            logger.error(f"Failed to start container: {e}")
            return {
                'error': str(e),
                'status': 'failed'
            }
    
    def stop_container(self, project_id: str, force_kill: bool = False):
        """Stop and remove project container, with option to force kill during build"""
        if not self.client:
            return {'status': 'no_client'}
            
        container_name = f"django-container-{project_id}"
        image_tag = f"django-project-{project_id}:latest"

        try:
            # Try to get the container
            container = self.client.containers.get(container_name)
            
            if force_kill:
                # Force kill immediately (useful during build interruption)
                logger.info(f"Force killing container {container_name}")
                container.kill()
                container.remove(force=True)
            else:
                # Graceful stop
                logger.info(f"Stopping container {container_name}")
                container.stop(timeout=10)
                container.remove(force=True)
                
            logger.info(f"Stopped and removed container {container_name}")
            
            # Also try to remove any intermediate/dangling images from build
            try:
                self.client.images.prune(filters={'dangling': True})
                logger.info("Cleaned up dangling images")
            except Exception as e:
                logger.warning(f"Could not clean up dangling images: {e}")
                
            return {'status': 'stopped'}
            
        except docker.errors.NotFound:
            logger.info(f"Container {container_name} not found")
            return {'status': 'not_found'}
        except Exception as e:
            logger.error(f"Error stopping/removing container: {e}")
            return {'status': 'error', 'error': str(e)}
    
    def execute_command(self, project_id: str, command: str) -> dict:
        """Execute a command in the project container"""
        if not self.client:
            return {'error': 'Docker client not available', 'success': False}
            
        container_name = f"django-container-{project_id}"
        print(container_name)
        try:
            container = self.client.containers.get(container_name)
            print(container)
            result = container.exec_run(command, workdir='/app')
            
            return {
                'exit_code': result.exit_code,
                'output': result.output.decode('utf-8'),
                'success': result.exit_code == 0
            }
        except docker.errors.NotFound:
            return {
                'error': 'Container not found. Please start the server first.',
                'success': False
            }
        except Exception as e:
            logger.error(f"Error executing command: {e}")
            return {
                'error': str(e),
                'success': False
            }
    
    def get_file_content(self, project_id: str, file_path: str) -> str:
        """Get content of a file from the project"""
        project_path = self.projects_dir / project_id / file_path
        
        try:
            with open(project_path, 'r', encoding='utf-8') as f:
                return f.read()
        except FileNotFoundError:
            return ""
        except Exception as e:
            logger.error(f"Error reading file: {e}")
            return f"Error reading file: {str(e)}"
    
    def save_file_content(self, project_id: str, file_path: str, content: str) -> bool:
        """Save content to a file in the project"""
        project_path = self.projects_dir / project_id / file_path
        
        try:
            # Create directory if it doesn't exist
            project_path.parent.mkdir(parents=True, exist_ok=True)
            
            with open(project_path, 'w', encoding='utf-8') as f:
                f.write(content)
            return True
        except Exception as e:
            logger.error(f"Error saving file: {e}")
            return False
    
    def list_project_files(self, project_id: str) -> list:
        """List all files in a project"""
        project_path = self.projects_dir / project_id
        files = []
        
        logger.info(f"Listing files for project {project_id}, path: {project_path}")
        logger.info(f"Projects dir: {self.projects_dir}")
        logger.info(f"Project path exists: {project_path.exists()}")
        
        if not project_path.exists():
            logger.warning(f"Project path does not exist: {project_path}")
            return files
        
        try:
            # Get absolute path to ensure we're within project boundaries
            abs_project_path = project_path.resolve()
            logger.info(f"Absolute project path: {abs_project_path}")
            
            for file_path in project_path.rglob('*'):
                if file_path.is_file() and not self._should_ignore_file(file_path):
                    # Ensure file is actually within project directory
                    abs_file_path = file_path.resolve()
                    try:
                        relative_path = abs_file_path.relative_to(abs_project_path)
                        files.append({
                            'path': str(relative_path),
                            'size': file_path.stat().st_size,
                            'modified': file_path.stat().st_mtime
                        })
                    except ValueError:
                        # File is outside project directory, skip it
                        logger.warning(f"Skipping file outside project directory: {abs_file_path}")
                        continue
                        
            logger.info(f"Found {len(files)} files in project {project_id}")
        except Exception as e:
            logger.error(f"Error listing files for project {project_id}: {e}")
        
        return files
    
    def _should_ignore_file(self, file_path: Path) -> bool:
        """Check if file should be ignored"""
        ignore_patterns = [
            '__pycache__',
            '.git',
            '.env',
            'Dockerfile',
            '.pyc',
            'db.sqlite3',
            'staticfiles',
            'media'
        ]
        
        path_str = str(file_path)
        return any(pattern in path_str for pattern in ignore_patterns)
    
    def _get_settings_module(self, project_path: Path) -> str:
        """Find the correct Django settings module name"""
        try:
            logger.info(f"Looking for Django settings in {project_path}")
            
            # Look for manage.py to find the project structure
            manage_py_path = project_path / 'manage.py'
            if manage_py_path.exists():
                logger.info(f"Found manage.py at {manage_py_path}")
                # Read manage.py to find the settings module
                with open(manage_py_path, 'r') as f:
                    content = f.read()
                    logger.info(f"manage.py content preview: {content[:200]}...")
                    
                # Extract the settings module from manage.py
                import re
                # Look for patterns like 'blog.settings' or "blog.settings"
                match = re.search(r"DJANGO_SETTINGS_MODULE.*?['\"]([^'\"]+)['\"]", content)
                if match:
                    settings_module = match.group(1).strip()
                    logger.info(f"Found settings module in manage.py: '{settings_module}'")
                    
                    # Validate the settings module format
                    if '.' in settings_module and not settings_module.startswith(','):
                        return settings_module
                    else:
                        logger.warning(f"Invalid settings module format: '{settings_module}', using fallback")
                
                # More specific pattern matching
                match = re.search(r"setdefault\(['\"]DJANGO_SETTINGS_MODULE['\"],\s*['\"]([^'\"]+)['\"]", content)
                if match:
                    settings_module = match.group(1).strip()
                    logger.info(f"Found settings module with setdefault pattern: '{settings_module}'")
                    return settings_module
            
            # Fallback: look for directories with settings.py
            logger.info("Manage.py not found or settings module not detected, looking for settings.py files")
            for item in project_path.iterdir():
                if item.is_dir() and (item / 'settings.py').exists():
                    settings_module = f"{item.name}.settings"
                    logger.info(f"Found settings.py in directory {item.name}, using {settings_module}")
                    return settings_module
            
            # Default fallback
            logger.warning("No Django settings module detected, using default 'settings'")
            return 'settings'
            
        except Exception as e:
            logger.error(f"Error finding settings module: {e}")
            return 'settings'
    
    def _find_available_port(self, start_port: int = 8001, max_attempts: int = 100) -> int:
        """Find an available port starting from start_port"""
        for port in range(start_port, start_port + max_attempts):
            try:
                with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                    s.bind(('localhost', port))
                    logger.info(f"Found available port: {port}")
                    return port
            except OSError:
                continue
        
        # Fallback to a higher range if all common ports are taken
        logger.warning(f"No ports found in range {start_port}-{start_port + max_attempts}, using fallback")
        return start_port + max_attempts